#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

source $SCRIPT_DIR/common.env

podcmd() {
  local map=$1
  local cmd=$2
  log $cmd
  podman exec -t $map manager $cmd
}

if [[ -z $1 ]]
then
  show | grep -v not
else
  cmd=$1
  shift
  echo -e "$_B$CLUSTER_ID"
  for map in ${1:-$(all)}
  do
    state $map
    if [[ ! -f $IN_CLUSTER ]]
    then
      log "${_R}is not in cluster$__"
    else
      case $cmd in
        start) # start ark server
          podcmd $map start
          touch $IS_RUNNING
          ;;

        stop) # stop ark server
          podcmd $map stop
          rm -f $IS_RUNNING
          ;;
      esac
    fi
  done
  show | grep -v not
fi
