---
- name: Ensure config directory eists
  ansible.builtin.file:
    path: "{{ asa_config_dir }}"
    state: directory

- name: Copy shared environment for all images
  ansible.builtin.copy:
    src: image.env
    dest: "{{ asa_config_dir }}"

- name: Copy environment for all maps
  ansible.builtin.template:
    src: maps.env
    dest: "{{ asa_config_dir }}"

- name: Copy environment for all maps
  ansible.builtin.template:
    src: maps.env
    dest: "{{ asa_config_dir }}"
