---
- name: Ensure directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ asa_config_dir }}"
    - "{{ asa_bin_dir }}"

- name: Copy shared environment
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ asa_config_dir }}"
  loop:
    - image.env
    - steamcmd.env
    - maps.env
    - manager.env
  notify: Restart Pod

- name: Copy local bin files
  ansible.builtin.copy:
    src: '../files/'
    dest: "{{ asa_bin_dir }}"
