- name: Create ASA pod
  containers.podman.podman_pod:
    name: asa
    state: quadlet
    quadlet_options: |
      [Unit]
      Description=Ark ASA Cluster

      [Service]
      Restart=always

      [Install]
      WantedBy=default.target
    network: host
    volumes:
      - steam2_data:/opt/steamcmd:z
      - shared2_cluster:/opt/cluster:z
      - server2_data:/opt/server:z
  notify: Reload Pod

- name: steamcmd container
  containers.podman.podman_container:
    name: steamcmd2
    image: localhost/kafka/steamcmd2
    state: quadlet
    quadlet_options: | 
      PodmanArgs=--env 'NOTIFY_SOCKET'
      Notify=true
      [Unit]
      Description=Steam CMD
    # TODO init_ctr: always
    detach: true
    env_file:
      - "%h/maps/env"
    pod: asa.pod
  notify: Reload Pod

- name: Create arkserver container one per map
  loop: "{{ asa_maps }}"
  loop_control:
    index_var: idx
  ansible.builtin.include_tasks: map.yml

- name: ensure ark asa server started
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
    state: started
    name: asa-pod
