- name: Create ASA pod
  containers.podman.podman_pod:
    name: asa
    state: quadlet
    quadlet_options: |
      [Unit]
      Description=Ark ASA Cluster

      [Service]
      Restart=always

      [Install]
      WantedBy=default.target
    network: host
    volumes:
      - shared_cluster:/opt/cluster:z
  notify: Restart Pod

- name: steamcmd container
  containers.podman.podman_container:
    name: steamcmd
    image: localhost/kafka/steamcmd2
    state: quadlet
    quadlet_options: | 
      PodmanArgs=--env 'NOTIFY_SOCKET'
      Notify=true
      [Unit]
      Description=Steam CMD
      [Service]
      TimeoutStartSec=7200
      TimeoutStopSec=70
    # TODO init_ctr: always
    detach: true
    volumes:
      - steam_data:/opt/steamcmd:z
      - server_data:/opt/server:z
    env_file:
      #- "%h/{{ asa_config_dir }}/steamcmd.env"
      - "{{ asa_config_dir }}/steamcmd.env"
    pod: asa.pod
  notify: Restart Pod

- name: Create arkserver container one per map
  loop: "{{ asa_maps }}"
  loop_control:
    index_var: idx
  ansible.builtin.include_tasks: map.yml

- name: ensure ark asa server started
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
    state: started
    name: asa-pod
